services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    environment:
      SECRET_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      RPC_URL: "http://localhost:61611/"
      PAYMENT_TOKEN_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      DATA_PAYMENTS_ADDRESS: "0x8464135c8F25Da09e49BC8782676a84730C318bC"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  autonomi:
    build:
      context: ..
      dockerfile: .devcontainer/autonomi/Dockerfile

    command: [ "sh", "-c", "cargo run --bin antctl local run --build --rewards-address=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 & sleep infinity" ]

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

volumes:
  postgres-data:
