[package]
name = "src-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
env_logger = "0.9"
log = "0.4"

autonomi-core = { path = "../crates/autonomi-core" }

color-eyre = "0.6" # For consistent error reporting, optional

# Pin problematic dependencies to stable versions to avoid "edition2024" issues.
base64ct = "1.6.0"
alloy-hardforks = "0.2.0" 