name: Deploy to DigitalOcean

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - web-deployment # This workflow runs on pushes to the web-deployment branch for testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and build frontend
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Specify the Node.js version you use
      - run: npm install
      - name: Build Frontend
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.DO_API_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_REGISTRY_USER }}
          password: ${{ secrets.DO_REGISTRY_PASSWORD }}

      - name: Force remove .dockerignore
        run: rm -f .dockerignore

      - name: Inspect build context
        run: |
          echo "Listing top-level files:"
          ls -l
          echo "Listing src-backend files:"
          ls -l src-backend
          echo "Listing autonomi-core files:"
          ls -l crates/autonomi-core

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/regru-marketplace/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_DROPLET_HOST }}
          username: ${{ secrets.DO_DROPLET_USER }}
          key: ${{ secrets.DO_DROPLET_KEY }}
          script: |
            # Log in to DigitalOcean Container Registry on the droplet
            echo "${{ secrets.DO_REGISTRY_PASSWORD }}" | docker login registry.digitalocean.com -u "${{ secrets.DO_REGISTRY_USER }}" --password-stdin

            # Pull the latest image from the registry
            docker pull registry.digitalocean.com/regru-marketplace/app:latest
            
            # Stop and remove the old container if it exists
            docker stop regru-app || true
            docker rm regru-app || true
            
            # Run the new container, exposing the port ONLY to the droplet's localhost
            docker run -d -p 127.0.0.1:8000:8000 --name regru-app \
              -e SECRET_KEY='${{ secrets.SECRET_KEY }}' \
              -e EVM_NETWORK='arbitrum-sepolia-test' \
              registry.digitalocean.com/regru-marketplace/app:latest
            
            # Gracefully restart Caddy to apply changes
            systemctl restart caddy 